### ISSUE TITLE
Please delete the bad words from your file!

### ISSUE THREAD

**Issue by akemmanuel** [david-star-git/cosmos#1]

**Comment by david-star-git** [comment]
Hello **akemmanuel**,

Thank you for reaching out. The provided word list is part of my bot's automatic content filtering system. It helps maintain a positive environment by automatically removing certain words from messages.

We understand that individual preferences may vary, and users have the flexibility to customize or remove this list based on their comfort level. If you find any words objectionable, you're welcome to modify the blacklist in your local version of the bot.

I appreciate your understanding and am here to assist with any further questions.

Best regards,
**David**

**Comment by akemmanuel** [comment]
Hello **david-star-git**,

You can use ```import badwords``` in your file and then create the file and make a function or a variable with the bad words!
